name: CI

on:
  pull_request: {}
  push:
    branches:
      - staging
      - trying
      - master

jobs:
  style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      # misspell fixer
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Fixes by misspell-fixer'
          title: 'Typos fix by misspell-fixer'
